version: '0.0.1'

services:
  db:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "9000:3306"
    env_file:
      - .env

  app:
    build: .
    container_name: game-server
    ports:
      - "9001:9000"
    environment:
      MYSQL_HOST: db
    env_file:
      - .env
    depends_on:
      - db

volumes:
  mysql_data: